spring.application.name=ledger
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update

# Where Kafka is running (e.g. via Docker)
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=ledger-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.properties.enable.idempotence=true
